### ISSUE TITLE
npm run build hangs at 95%

### ISSUE THREAD

**Issue by mrudangit** [antonybudianto/angular-webpack-starter#102]
C:\JettWebPack\webPack>
C:\JettWebPack\webPack>npm run build

> angular-webpack-starter@2.0.0-rc.1 prebuild C:\JettWebPack\webPack
> npm run clean:build

> angular-webpack-starter@2.0.0-rc.1 clean:build C:\JettWebPack\webPack
> rimraf dist

> angular-webpack-starter@2.0.0-rc.1 build C:\JettWebPack\webPack
> webpack --config config/webpack/webpack.prod.js --progress --profile --bail

APP_ENV is "development"
21389ms building modules
120ms sealing
4ms optimizing
3ms basic module optimization
190ms module optimization
15ms advanced module optimization
28ms basic chunk optimization
4ms chunk optimization
7ms advanced chunk optimization
3ms module and chunk tree optimization
95ms module reviving
82ms module order optimization
11ms module id optimization
8ms chunk reviving
3ms chunk order optimization
32ms chunk id optimization
60ms hashing
5ms module assets processing
255ms chunk assets processing
10ms additional chunk assets processing
6ms recording
19158ms additional asset processing
100ms chunk asset optimization
314ms asset optimization
 95% emitting

**Comment by antonybudianto** [comment]
see #74
