### ISSUE TITLE
404 errors after changes with HMR

### ISSUE THREAD

**Issue by theentirety** [antonybudianto/angular-webpack-starter#106]
## Issue Overview
After making changes to the .ts or .html file for a component and HMR running via `npm start`, get http://localhost:8080/component.html not found 404

## Issue Description
Randomly after working in the project for a while and making saves and updates, the HRM will fail with an error on a Promise for polyfills.dll.js
```
GET http://localhost:8080/<component>.html 404 (Not Found)
scheduleTask @ polyfills.dll.js:8723
ZoneDelegate.scheduleTask @ polyfills.dll.js:7586
Zone.scheduleMacroTask @ polyfills.dll.js:7512
(anonymous) @ polyfills.dll.js:8746
send @ VM1008:3
ResourceLoaderImpl.get @ vendorDll.dll.js:39976
DirectiveNormalizer._fetch @ vendorDll.dll.js:20214
DirectiveNormalizer.normalizeTemplateAsync @ vendorDll.dll.js:20248
DirectiveNormalizer.normalizeTemplate @ vendorDll.dll.js:20228
CompileMetadataResolver._loadDirectiveMetadata @ vendorDll.dll.js:21474
(anonymous) @ vendorDll.dll.js:21715
(anonymous) @ vendorDll.dll.js:21630
CompileMetadataResolver.loadNgModuleMetadata @ vendorDll.dll.js:21630
RuntimeCompiler._loadModules @ vendorDll.dll.js:33055
RuntimeCompiler._compileModuleAndComponents @ vendorDll.dll.js:33025
RuntimeCompiler.compileModuleAsync @ vendorDll.dll.js:33015
PlatformRef_._bootstrapModuleWithZone @ vendorDll.dll.js:23869
PlatformRef_.bootstrapModule @ vendorDll.dll.js:23851
startApp @ main.ts:18
ZoneDelegate.invoke @ polyfills.dll.js:7573
Zone.run @ polyfills.dll.js:7455
(anonymous) @ polyfills.dll.js:7843
ZoneDelegate.invokeTask @ polyfills.dll.js:7606
Zone.runTask @ polyfills.dll.js:7495
drainMicroTaskQueue @ polyfills.dll.js:7742

polyfills.dll.js:7729 Unhandled Promise rejection: Failed to load <component>.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load <component>.html undefined
consoleError @ polyfills.dll.js:7729
_loop_1 @ polyfills.dll.js:7758
drainMicroTaskQueue @ polyfills.dll.js:7762
ZoneTask.invoke @ polyfills.dll.js:7680
polyfills.dll.js:7731 Error: Uncaught (in promise): Failed to load <component>.html
    at resolvePromise (polyfills.dll.js:7809)
    at resolvePromise (polyfills.dll.js:7794)
    at polyfills.dll.js:7843
    at ZoneDelegate.invokeTask (polyfills.dll.js:7606)
    at Zone.runTask (polyfills.dll.js:7495)
    at drainMicroTaskQueue (polyfills.dll.js:7742)
    at XMLHttpRequest.ZoneTask.invoke (polyfills.dll.js:7680)
```
Once this occurs, it's impossible to fix no matter how many times I rebuild the dlls or re-run `npm start` or empty the browser cache.

## Reproducables
Very difficult to reproduce and have not been able to guarantee reproduction. Only solution has been to full re-clone the repo and start over with a new `npm i`. It works for a while and then will crash again and never come back.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX 	|
| **Node version**     	| 6.9.2   	|
| **NPM Version**      	| 3.10.9    	|
| **Environment**       | Browser          |

**Comment by antonybudianto** [comment]
@theentirety , Sorry, can you share your repo? 
Also I assume you use `./` for all templateUrls right?

**Comment by theentirety** [comment]
Sorry, but I can't share the repo. I'm not sure which version as I didn't create the repo, but it was within the last week. Yes, all of the paths use `./` for the templateUrls.

**Comment by antonybudianto** [comment]
can you try on latest rc.1 starter? @theentirety

**Comment by theentirety** [comment]
Yes, I'm fully up to date and just pulled in the latest changes (jit) and still having the problem. Here is the output from `npm run stat`:

```
Angular Webpack Starter  1.0.0 
Environments:
- Loaded  13  values from  .env  file
- NODE_ENV:  undefined 
- APP_ENV:  local 

Dependencies:
- Main Dependencies:  73 
- Dev Dependencies:  16 

Application:
- module:  47 
- component:  46 
- pipe:  1 
- directive:  0 
- routes:  12 
- spec:  2 
- e2e spec:  1 
```

As for the `rc1` tag, I could certainly clone that and I'm sure it will run, but we've already pulled in a lot of code and I won't be able to repro. Unless there is a way to merge it in...

**Comment by antonybudianto** [comment]
I see, so you `local` for `APP_ENV`, while by default, I use `development` for HMR activation, you can update it here, and try again
https://github.com/antonybudianto/angular-webpack-starter/blob/master/src/main.ts#L14

**Comment by theentirety** [comment]
I think I've narrowed it down to an issue with typescript and the `tsconfig` file. Your environment suggestion is unrelated. I am trying to get local typescript development to work properly with node, but when I added/modified the `tsconfig` to change from:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es6",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "awesomeTypescriptLoaderOptions": {
        "useWebpackText": true
    },
    "exclude": [
        "node_modules",
        "coverage",
        "config",
        "dist",
        "report"
    ]
}
```

to:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es6",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "typeRoots": [
            "../node_modules/@types"
        ],
        "types": [
            "core-js",
            "node"
        ]
    },
    "awesomeTypescriptLoaderOptions": {
        "useWebpackText": true
    },
    "exclude": [
        "node_modules",
        "coverage",
        "config",
        "dist",
        "report"
    ]
}
```

My change allows for my IDE (atom) to properly handle the typescript, but it causes the missing files error (I think). However, upon reverting the file, the errors persist. I've tried cleaning the dll, but there is something that is not compiling properly. Still investigating...

**Comment by antonybudianto** [comment]
No, it's related if you don't update https://github.com/antonybudianto/angular-webpack-starter/blob/master/src/main.ts#L14 to `local`, since it won't do hmrBootstrap at all if the env is mismatched

**Comment by theentirety** [comment]
We changed the name of the variable in the .env file to match so it is `APP_ENV=local` in the `.env` file. If there are other hidden places where the environment is hardcoded, please tell me so that I can make sure this is updated, but the starter should allow for the environment name to be changed without failing.

**Comment by antonybudianto** [comment]
i put environmental on `main.ts` and `polyfills.ts`

**Comment by antonybudianto** [comment]
I'm confused on `"../node_modules/@types"`, do you change around the starter structure? 
If so, then I can't help much, sorry.

**Comment by theentirety** [comment]
I'm fairly convinced this is an issue with Atom playing nice with TypeScript and Webpack. Atom is having problems dealing with the node modules and the webpack config is very specific and they don't work well. I think the bug is actually making the starter work with Atom properly. I think there are some configs that need to be set to make that happen, but I haven't had much luck yet getting it to work.
