### ISSUE TITLE
404 boostrap.css.map

### ISSUE THREAD

**Issue by tnsasse** [antonybudianto/angular-webpack-starter#11]
## Issue Overview
Running the starter, as described in the Readme, I receive an error in the browser, stating that `bootstrap.css.map` was not found. Is that something to worry about?

## Issue Description
HTTP 404 for http://localhost:8080/bootstrap.css.map

## Reproducables
  - Downloaded the starter 
  - `npm install`
  - `npm run env`
  - `npm start`
  - Point browser to `localhost:8080' and opened the console.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OS X 	|
| **Node version**     	| v6.3.1   	|
| **NPM Version**      	| v3.10.7    	|
| **Environment**       | Browser          |

**Comment by antonybudianto7** [comment]
What browser did you use? @tnsasse 
I'm trying to reproduce now

**Comment by tnsasse** [comment]
Safari Version 9.1.2 (11601.7.7)

Good catch: it doesn't appear in Chrome!

**Comment by antonybudianto7** [comment]
I also can't reproduce it in Chrome

**Comment by tnsasse** [comment]
Haha, okay I think it won't be something major than. Thanks for the quick response.
