### ISSUE TITLE
how to make image assets determined during runtime?

### ISSUE THREAD

**Issue by yuan-java** [antonybudianto/angular-webpack-starter#126]
I have the following piece of code, the image is not determined until the code is running in the browser. I noticed that when I compiled the code, I have to set the real file name of the image. So how can I achieve the feature of my code? Thank you so much!

```
        <div *ngFor="let module of moduleList; let i = index">
            <div *ngIf="module[1]" style="margin-bottom: 48px;" class="col-xs-4 col-sm-3 col-md-3 text-center">
                <a routerLink={{module[2]}}>
                    <img src="../../images/features/{{i}}.jpg" class="img-responsive center-block"
                         alt="{{module[0]}}">
                    <label>{{module[0]}}</label>
                </a>
            </div>
        </div>
```

**Comment by antonybudianto7** [comment]
https://stackoverflow.com/questions/35737540/angular-2-dynamic-images

**Comment by yuan-java** [comment]
Thanks. It can be solved by using 
`<img [src]="urlVariable" />`
