### ISSUE TITLE
package.json unmet dependencies

### ISSUE THREAD

**Issue by briangann** [antonybudianto/angular-webpack-starter#6]
## Issue Overview
npm dependency problem with webpack/webpack-dev-server

## Issue Description
npm install fails with unmet dependencies:

npm WARN webpack-dev-server@1.16.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.

(does not detect installed webpack 2.1.0-beta.24)

## Reproducables
clone repo, npm install

update webpack and webpack-dev-server to v2 beta works:
```
diff --git a/package.json b/package.json
index 3ce9c60..9d8ee49 100644
--- a/package.json
+++ b/package.json
@@ -107,7 +107,7 @@
     "tslint-loader": "^2.1.5",
     "typescript": "^2.0.2",
     "typings": "^1.3.3",
-    "webpack": "2.1.0-beta.24",
+    "webpack": "^2.1.0-beta.25",
     "webpack-merge": "^0.14.1",
     "zone.js": "^0.6.21"
   },
@@ -120,7 +120,7 @@
     "protractor": "4.0.8",
     "ts-node": "^1.3.0",
     "webpack-dashboard": "^0.1.8",
-    "webpack-dev-server": "^1.14.1",
+    "webpack-dev-server": "2.1.0-beta.5",
     "yargs": "^5.0.0"
   }
-}
\ No newline at end of file
+}
```
## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 	|
| **Node version**     	| 6.6.0   	|
| **NPM Version**      	| 3.10.3    	|
| **Environment**       | Browser          |

**Comment by antonybudianto7** [comment]
can you create a PR for that? I'll take a look later, thanks

**Comment by tnsasse** [comment]
Same issue, and the proposed fix worked for me. @briangann please submit a PR, thanks.
