### ISSUE TITLE
the gulp-cssnano changes the z-index of the minified css files

### ISSUE THREAD

**Issue by ovione** [antonybudianto/angular-webpack-starter#71]
## Issue Overview
the gulp-cssnano changes the z-index of the minified css files

## Issue Description
this happens when we issue a 'gulp build'

The solution I found is in the build.js in the task 'build-assets' to add to the 'gulp-cssnano' plugin the following:
cssnano({zindex: false})
that means that the minification will not touch the z-indexes.

**Comment by antonybudianto7** [comment]
wrong repo, please post it to https://github.com/antonybudianto/angular2-starter

also I'd love to accept your PR :smile:
