### ISSUE TITLE
Development not defined

### ISSUE THREAD

**Issue by WVWillHall** [antonybudianto/angular-webpack-starter#92]
## Issue Overview
Cloning repo and starting from scratch, simple issue found around "development not defined"

## Issue Description
DefinePlugin treats passed config values poorly.

```
    new webpack.DefinePlugin({
      'process.env': "'envMap'"
    }),
```

fixes the issue. (rebuild dll and rerun)

## Reproducables
Two different machines, same issue.

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| OSX 	|
| **Node version**     	| 4.x  	|
| **NPM Version**      	| 4.x    	|
| **Environment**       | Browser          |

**Comment by antonybudianto** [comment]
Hi,

Do you create `.env` after you clone the starter?

I'll investigate it more
